name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  source-dependencies:
    description: 'Yaml file containing dependencies to be downloaded with Vcstool and installed from source. Remember to add extra apt dependencies above.'
    required: false
    default: ''
  codecov-token:
    description: 'Token to upload to Codecov'
    required: false
    default: ''
  script-before-cmake:
    description: 'Bash script to be run before cmake inside the build folder'
    required: false
    default: ''
  script-between-cmake-make:
    description: 'Bash script to be run after cmake and before make inside the build folder'
    required: false
    default: ''
  script-after-make:
    description: 'Bash script to be run after make and before make test inside the build folder'
    required: false
    default: ''
  script-after-make-test:
    description: 'Bash script to be run after make test inside the build folder'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.source-dependencies }}
    - ${{ inputs.codecov-token }}
    - ${{ inputs.script-before-cmake }}
    - ${{ inputs.script-between-cmake-make }}
    - ${{ inputs.script-after-make }}
    - ${{ inputs.script-after-make-test }}
