name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  collection-file:
    description: 'Collection to build'
    required: false
    default: 'colleciton-dome.yaml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.collection-file }}
