name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  codecov-enabled:
    description: 'Prepare the build for coverage and execute codecov'
    required: false
    default: ''
  codecov-token-private-repos:
    description: 'Token to upload to codecov in private repositories. Public repos do not need it'
    required: false
    default: ''
  codecov-token:
    description: 'DEPRECATED: use codecov-token-private if using private repositories'
    required: false
    default: ''
    deprecationMessage: 'Public repositories do not need codecov-token, use codecov-enabled to run codecov on Public repositories. To facilitate transition codecov is enabled but not using any token'
  cmake-args:
    description: 'Additional CMake arguments to use when building package under test'
    required: false
    default: ''
  script-before-cmake:
    description: '(Deprecated) Bash script to be run before cmake inside the build folder'
    required: false
    default: ''
  script-between-cmake-make:
    description: '(Deprecated) Bash script to be run after cmake and before make inside the build folder'
    required: false
    default: ''
  script-after-make:
    description: '(Deprecated) Bash script to be run after make and before make test inside the build folder'
    required: false
    default: ''
  script-after-make-test:
    description: '(Deprecated) Bash script to be run after make test inside the build folder'
    required: false
    default: ''
  doxygen-enabled:
    description: 'Run doxygen documentation checks.'
    required: false
    default: ''
  tests-enabled:
    description: 'Run tests.'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.codecov-enabled }}
    - ${{ inputs.codecov-token-private-repos }}
    - ${{ inputs.codecov-token }}
    - ${{ inputs.cmake-args }}
    - ${{ inputs.doxygen-enabled }}
    - ${{ inputs.tests-enabled }}
