name: 'Ignition install'
description: ''
author: "Louise Poubel"
inputs:
  github_token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  apt-dependencies:
    description: 'Dependencies to apt install'
    required: false
    default: ''
  codecov-token:
    description: 'Token to upload to Codecov'
    required: false
    default: ''
  cmake-args:
    description: 'Additional CMake arguments to use when building package under test'
    required: false
    default: ''
  script-before-cmake:
    description: '(Deprecated) Bash script to be run before cmake inside the build folder'
    required: false
    default: ''
  script-between-cmake-make:
    description: '(Deprecated) Bash script to be run after cmake and before make inside the build folder'
    required: false
    default: ''
  script-after-make:
    description: '(Deprecated) Bash script to be run after make and before make test inside the build folder'
    required: false
    default: ''
  script-after-make-test:
    description: '(Deprecated) Bash script to be run after make test inside the build folder'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apt-dependencies }}
    - ${{ inputs.codecov-token }}
    - ${{ inputs.cmake-args }}
